blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("articles/<slug:article_slug>/", views.post, name='article'),
    path("categories/<slug:category_slug>/", views.category, name='category'),
]

personal/urls.py
from django.urls import include, path

from . import views

app_name = "personal"

urlpatterns = [
    path("", views.index, name="index"),
    path("resume/", views.resume, name="resume"),
    path("404/", views.error_404, name="404"),
    path("50x/", views.error_50x, name="50x"),
]

projects/urls.py
from django.urls import include, path

from . import views

app_name = "projects"

urlpatterns = [
    path("", views.index, name="index"),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", include("personal.urls", namespace="personal")),
    #path("blog/", include("blog.urls", namespace="blog")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField(max_length=128, db_index=True)
    description = models.CharField(max_length=256)
    slug = models.SlugField(max_length=128, db_index=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Article(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name="articles")

    title = models.CharField(max_length=128)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    slug = models.SlugField(max_length=128, unique=True)
    published = models.BooleanField(default=False)
    description = models.CharField(max_length=256, default="")

    creation_date = models.DateTimeField('date created', db_index=True)
    publish_date = models.DateTimeField('date published', db_index=True)
    updated_date = models.DateTimeField('date updated', db_index=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from blog.models import Category, Tag

# Create your models here.

class Project(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name="projects")

    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, unique=True)
    published = models.BooleanField(default=False) # visible or not
    description = models.TextField() # shorter description 
    content = models.TextField(default="") # longer description shown on project page

    creation_date = models.DateTimeField('date created', db_index=True)
    publish_date = models.DateTimeField('date published', db_index=True)
    updated_date = models.DateTimeField('date updated', db_index=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class Link(models.Model):
    name = models.CharField(max_length=128)
    link = models.CharField(max_length=2083)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category

import markdown

# use this to get a short blurb from a block of text
def get_blurb(content, max_word_count=50, average_word_char=7):
    max_char_count = max_word_count * average_word_char

    space_count = 0
    char_count = 0
    for c in content:
        if c == " ":
            space_count += 1
        if space_count >= max_word_count:
            # using spaces to count words
            return content[:char_count]
        if char_count == max_char_count:
            # prevents from parsing for too long
            return content[:char_count] + "-"
        char_count += 1

    # if max_word_count was larger than the given text
    return content


def index(request):
    max_article_list_len = 10
    article_list = []

    for article in Article.objects.order_by('-publish_date'):
        if not article.published:
            continue

        article.content = get_blurb(article.content)
        article_list.append(article)

        if len(article_list) >= max_article_list_len:
            break
    return render(request, "blog/index.html", {"article_list": article_list})


def post(request, article_slug):
    article = get_object_or_404(Article, slug__exact=article_slug, pk__gt=0)
    article.content = markdown.markdown(
        article.content,
        extensions=[
            'markdown.extensions.codehilite',
            'markdown.extensions.fenced_code',
            'markdown.extensions.sane_lists',
        ]
    )
    context = {'article': article}
    return render(request, 'blog/article.html', context)


def category(request, category_slug):
    category = get_object_or_404(Category, slug__exact=category_slug, pk=1)
    return render(request, 'blog/category.html', {'category': category})

personal/views.py
from django.http import Http404
from django.shortcuts import render


def index(request):
    return render(request, "personal/index.html")


def links(request):
    return render(request, "personal/links.html")


def resume(request):
    return render(request, "personal/resume.html")


def error_404(request):
    return render(request, "404.html")


def error_50x(request):
    return render(request, "50x.html")

projects/views.py
from django.shortcuts import render
from .models import Project, Link

# Create your views here.

def index(request):
    max_list_len = 10
    project_list = []

    for project in Project.objects.order_by('-creation_date'):
        if not project.published:
            continue
        project.links = Link.objects.filter(project__exact=project)
        project_list.append(project)
        if len(project_list) >= max_list_len:
            break

    return render(request, "projects/index.html", {"project_list": project_list})

website/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/article.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}{{article.title}}{% endblock title %}
{% block description %}Written by {{article.author.first_name}} {{article.author.last_name}} on {{article.publish_date.date}}{% endblock description %}
{% block additional_css %}
<link rel="stylesheet" href="{% static "blog/stylesheet.css" %}" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="{% static "blog/codeblock.css" %}" type="text/css" media="screen" charset="utf-8">{% endblock %}
{% block custom_fonts%}
<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="article">
    <div><h1 class="article-title">{{article.title}}</h1></div>
    <div class="article-author">Written by {{article.author.first_name}} {{article.author.last_name}} on {{article.publish_date.date}}, about {{article.publish_date|naturaltime}}</div>
    
    <div class="article-content">
        {{article.content|safe}}
    </div>

    {% if article.author.email %}
        <div class="article-author"><p>If you liked this article or have any questions, please feel free to shoot me an <a href="mailto:{{article.author.email}}">email</a></p></div>
    {% endif %}
</div>

{% endblock content %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Blog{% endblock title %}
{% block description %}Blog articles by Nick Hirzel{% endblock description %}
{% block additional_css %}<link rel="stylesheet" href="{% static "blog/stylesheet.css" %}" type="text/css" media="screen" charset="utf-8">{% endblock %}

{% block content %}
{% if article_list %}
<div class="listing-article">
    {% for article in article_list %}
        {% if article %}
            <div class="blurb">
                <div class="blurb-info">
                    <div class="blurb-title">
                        <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a>
                    </div>
                    <div class="blurb-author">
                        {{article.author.first_name}} {{article.author.last_name}} on {{article.publish_date.date}}
                    </div>
                </div>
                <div class="blurb-description">
                    {{article.description}}
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% else %}
    <p>No articles available</p>
{% endif %}
{% endblock content %}

personal/templates/50x.html
{% extends "base.html" %}
{% load static %}

{% block title %}500 Error{% endblock title %}
{% block description %}500 Level Error{% endblock description %}

{% block content %}
<div class="error">
    <div class="title"><h2 class="error">500 Level Error</h2></div>
    <p>Something went wrong, sorry!</p>
</div>
{% endblock content %}

personal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111523511-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-111523511-1');
</script>

<meta name="wot-verification" content="6954e25e2f43a10d4eff"/>

<meta name="keywords" content="Nick,Hirzel,Programming,Programmer,Code,Coding,C++,C,Java,Golang,Personal,Blog,Resume,Job,Experience">
<meta name="author" content="Nick Hirzel">
<meta name="description" content="{% block description %}{% endblock description %}">
<meta charset="UTF-8">

<title>{% block title %}{% endblock title %}</title>

<link rel="stylesheet" href="{% static "stylesheet.css" %}" type="text/css" media="screen" charset="utf-8">
{% block additional_css %}{% endblock %}
{% block custom_fonts%}{% endblock %}
<link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}"/>
</head>

<body>
<div class="wrap">
<header>
    <div class="navbar">
        <div class="navtitle">
            <a href="{% url 'personal:index' %}">nick hirzel</a>
        </div>
        <div>
            <nav class="navcontent">
            <a href="{% url 'personal:index' %}">home</a>
            <span class="middot">&middot;</span>
<!--        
            <a href="/blog/">blog</a>
            <span class="middot">&middot;</span>
-->
            <a href="/projects/">projects</a>
            <span class="middot">&middot;</span>
            <a href="{% url 'personal:resume' %}">resume</a>
            </nav>
        </div>
    </div>
</header>

<div class="hr"></div>

{% block content %}
{% endblock content %}

<div class="hr"></div>
    <footer>
        <div class="footer">
            <div class="footer-links">
                <a href="https://gitlab.com/kwask">GitLab</a>
                <span class="middot">&middot;</span>
                <a href="https://github.com/Kwask">GitHub</a>
                <span class="middot">&middot;</span>
                <a href="https://www.youtube.com/channel/UCq1wbvoyM7R4dBEK4BDGR5Q">YouTube</a>
                <span class="middot">&middot;</span>
                <a href="https://twitter.com/_kwask">Twitter</a>
            </div>
            <div>
                &copy; 2014-{% now "Y" %}, Nick Hirzel
            </div>
        </div>
    </footer>
</div>
</body>
</html>

personal/templates/personal/dunder.html
<!DOCTYPE html>
<html>
<head>
    <meta name="author" content="Charles Hirzel">
    <meta name="description" content="Coming Christmas 2002!">
    <meta charset="UTF-8">
    
	<title>Dunder Miffilin</title>
</head>
<body>
	<center>
        <h1>Under Construction</h1>
        <img src="media/jackhammer.gif">
        <p>Coming Christmas 2002!</p>
	</center>
</body>
</html>

personal/templates/personal/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Nick Hirzel{% endblock title %}
{% block description %}Programming projects and other stuff by Nick Hirzel{% endblock description %}

{% block content %}
    <div class="row">
        <div class="greeting">
            <p class="greeting">Hey! I'm Nick Hirzel</p>
            <p class="greeting">I'm a college student currently working towards a computer science degree. In my spare time I like to do game dev.</p>
            <p class="greeting">If you'd like to contact me, the easiest way is by <a href="mailto:nhirzel1@gmail.com">email</a>.</p>
        </div>
    </div>
{% endblock content %}

personal/templates/personal/links.html
{% extends "base.html" %}

{% block title %}Links{% endblock title %}
{% block description %}Links for useful stuff{% endblock description %}

{% block content %}
<p class="links-desc">These are links that are either related to work that I do, or resources that I find valuable.</p>

<!--
<div class="links-list">
    <ul>
    <li><a href="#mylinks">My Links</a></li>
    <li><a href="#tutorials">Tutorials</a></li>
    <li><a href="#tools">Tools</a></li>
    <li><a href="#youtube">YouTube Channels</a></li>
    </ul>
</div>
-->

<div class="links-list">
    <h2 id="mylinks" class="links">My Links</h2>
    <ul>
    <li><a href="https://gitlab.com/kwask">GitLab</a>: My active git repos, check this for my current projects</li>
    <li><a href="https://github.com/Kwask">GitHub</a>: My old git repos, really only for inactive stuff</li>
    <li><a href="https://www.youtube.com/channel/UCq1wbvoyM7R4dBEK4BDGR5Q">YouTube</a>: Sometimes I'll post development videos</li>
    <li><a href="https://www.twitch.tv/kwask">Twitch</a>: Development streams, usually during Ludum Dare</li>
    <li><a href="https://twitter.com/_kwask">Twitter</a>: Used rarely, but I'm making an effort to use it more</li>
    </ul>
</div>
    
<div class="links-list">
    <h2 id="tutorials" class="links">Tutorials</h2>
    <ul>
    <li><a href="https://open.gl/">open.gl</a>: Great tutorial series for an intro to OpenGL</li>
    <li><a href="https://learnopengl.com/">learnopengl.com</a>: Another great tutorial series, covers a greater breadth of concepts</li>
    <li><a href="https://www.youtube.com/watch?v=tvC1WCdV1XU&list=PLAE85DE8440AA6B83">thenewboston</a>: "Bucky's C++" tutorials is one of the biggest things that help me get into programming. Incredible tutorial series for C++ beginners</li>
    </ul>
</div>

<div class="links-list">
    <h2 id="tools" class="links">Tools</h2>
    <ul>
    <li><a href="https://ninite.com/">ninite.com</a>: A great tool for installing vital Windows programs on a fresh install</li>
    </ul>
</div>

{% endblock content %}
 

personal/templates/personal/resume.html
{% extends "base.html" %}
{% load static %}

{% block title %}Resume{% endblock title %}
{% block description %}Nick Hirzel's Resume{% endblock description %}

{% block content %}
<object data="{% static "personal/nick_hirzel_resume.pdf" %}" type="application/pdf" width="750" height="800">
	<a href="{% static "personal/nick_hirzel_resume.pdf" %}">nick_hirzel_resume.pdf</a>
</object>
{% endblock content %}

projects/templates/projects/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Projects{% endblock title %}
{% block description %}Projects created by Nick Hirzel{% endblock description %}

{% block content %}
{% if project_list %}
{% for project in project_list %}
    {% if project and project.links %}
    <div class="project">
        <div class="project-details">
            <div class="project-title"><p>{{project.title}}</p></div>
            <div class="project-desc"><p>{{project.description}}</p></div>
        </div>
        <div class="project-links">
            <p>Links</p>
            {% for link in project.links %}
            {% if link %}
            <a href="{{link.link}}">{{link.name}}</a>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endfor %}
{% else %}
<p>No projects</p>
{% endif %}
{% endblock content %}